### ISSUE TITLE
[Discussion] What do you think about the Atomic Design?

### ISSUE THREAD

**Issue by HelloEdit** [infinitered/ignite-ir-boilerplate-andross#106]
Today, I just discovered the [Atomic Design](http://bradfrost.com/blog/post/atomic-web-design/)

I think it's good method of working, I do not know if to create a react application on this design is really practical.

Maybe the ignite-boilerplate could be inspired by it 😄

**Comment by skellock** [comment]
I took a run at Atomic Design on a project and wasn't overly happy with how it turned out.  I'm sure 100% of that dissatisfaction was brought on my me doing it wrong tho.  The lines between my molecules and organisms were too blurry.

You could certainly create your own boilerplate to do this.

If you do, please lemme know.  I'm very interested in this!
