### ISSUE TITLE
The fate of git hooks lies with you, champion.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite-ir-boilerplate-andross#120]
Some action to take from this [issue](https://github.com/infinitered/ignite/issues/1122).

* @jamonholmgren wants hooks gone.
* @skellock wants this to be lint-on-commit & test-on-push + `lint-staged`.
* @ckeeney wants CI to handle this.
* Not clear on what @gantman wants but he I know he votes this to be a plug-in.

There’s probably more opinions out there too.

A reasonable first step be to hide current functionality behind `--with-git-hooks`.

Any objections?

**Comment by jamonholmgren** [comment]
![objection](https://media.tenor.com/images/8b55fb889c9bf29342a8797219a318b6/tenor.gif)

FWIW I like to run linting in VS Code and tests manually + in CI. (Hint: FWIW -- it's worth very little here)

**Comment by ryanlntn** [comment]
Since there were no objections I'm going to make git hooks optional and update the behavior to lint on commit and test on push + lint-staged.

**Comment by jamonholmgren** [comment]
I'm not super worried about this, so don't take my opinion too seriously.

**Comment by yordis** [comment]
In my personal experience, I really dislike when people put the linter on commit or push.

When you want to get things done, specially when you are newbie to how the company works and the standards) is really annoying to have the linter rejecting you from commit or push.

Now,

This happens to me because I would normally create my own branches, by so, I will make sure before it gets into the `master` or whatever other branch that you push when you finish the work, I like to squash and clean up my work, so that is why I do care about no having down time for committing or pushing.

But,

At that moment, I wouldn't mind if the CI let me know that I forgot to run the linters and test, that is the value added to the CI anyway.

FWIW, your IDEs will help you with the on time fixes with the plugins which will let you know sometimes what is wrong.

**Comment by skellock** [comment]
Ya, coming back to this ticket nearly 9 months later...  I'm with @yordis and @ckeeney on this.

Lint-on-stage is a problem for staging parts of a file.

And test-on-commit is a problem for commiting the small changes while still wip'ing other things.

🤷‍♂️ 🤷‍♀️ 🤷‍♂️ 🤷‍♀️ 🤷‍♂️ 🤷‍♀️ 🤷‍♂️ 🤷‍♀️ 🤷‍♂️ 🤷‍♀️ 🤷‍♂️ 🤷‍♀️

**Comment by ryanlntn** [comment]
@skellock So you're on team no hooks now too? If so I'll just axe them.

**Comment by skellock** [comment]
I think so ya. I know of 4 projects in the last year we’ve done where someone has said, “what’s going on here”?

Can we replace it with a prompt that says: do you promise to install CI (Y/n)?

**Comment by jamonholmgren** [comment]
Next time @skellock and I disagree I'll just snooze an issue for 9 months and ask again. ;-)
