### ISSUE TITLE
Relay support

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/ignite-ir-boilerplate-andross#180]
Hey guys any plans on React-Relay support or if any plans on moving towards relay way of client side data handling?

**Comment by Amurmurmur** [comment]
Ok I think its been a while and I didnt get my answer back, which makes me realise its better not to leave the trash in the issues and just close this issue.

**Comment by GantMan** [comment]
Sorry. Weve been busy. Currently more apollo codethan relay.  We will see.

**Comment by jamonholmgren** [comment]
@Amurmurmur Sorry about the lack of response on this issue. Most of our team has been working on client projects or our new [Bowser](https://github.com/infinitered/ignite-ir-boilerplate-bowser) boilerplate, so that's probably how we missed it.

We really like Apollo and will probably be experimenting with that in projects. Technologies that perform well in our client projects then get introduced into our public boilerplate, so if our experiments with GraphQL go well, you can expect to see Apollo (or something like it) in a future boilerplate.

**Comment by Amurmurmur** [comment]
@GantMan @jamonholmgren 
Thank you so much guys for getting back to me.
Yeah the new boilerplate is a nice peace of work! Ill definitely check it out!

Will wait on your Apollo feed back once you decide to go for it 👍
